refactor: add private properties in User
lonnieezell/codeigniter-shield pull request #74
Opened 2022-04-25 07:28 UTC by kenjis

Ref #65

2022-04-25 12:15 UTC, MGatner requested changes

2022-04-25 12:31 UTC, kenjis commented on src/Authentication/Traits/UserProvider.php
> +                ->first();
Yes. The purpose is to set the private properties. See the below code.
I also moved the `foreach` up, because it is common logic for later code.

2022-04-25 12:51 UTC, MGatner commented on src/Authentication/Traits/UserProvider.php
> +                ->first();
💪

2022-04-26 00:39 UTC, kenjis commented on src/Entities/User.php
> +    private array $identities = [];
Done.

2022-04-26 00:40 UTC, kenjis commented on src/Entities/User.php
> +        if ($this->identities === []) {
Done.

2022-04-26 11:45 UTC, MGatner approved these changes

2022-04-27 03:16 UTC, lonnieezell approved these changes

2022-04-27 03:16 UTC, merged