docs: hander -> authenticator
lonnieezell/codeigniter-shield pull request #75
Opened 2022-04-25 08:32 UTC by kenjis

Ref #67

First, remove **handler** from the documentation.

2022-04-25 12:21 UTC, MGatner requested changes
Definite improvement. A couple small suggestions.

2022-04-25 12:21 UTC, MGatner commented on docs/2 - authentication.md
> +If `allowRemembering` is `true` in the `Auth` config file, you can tell the Session Authenticator
I don't care about the casing but it should be consistent. 
```suggestion
If `allowRemembering` is `true` in the `Auth` config file, you can tell the Session authenticator
```

2022-04-25 12:21 UTC, MGatner commented on docs/2 - authentication.md
> +`Session` and `AccessTokens`, respectively. The `chained` filter will check both authenticators in sequence
```suggestion
use to protect your routes, `session`, `tokens`, and `chained`. The first two cover the `Session` and `AccessTokens` authenticators, respectively. The `chained` filter will check both authenticators in sequence
```

2022-04-26 00:23 UTC, kenjis commented
@MGatner Thanks!

2022-04-26 03:13 UTC, lonnie-vault approved these changes

2022-04-26 03:14 UTC, merged